parameters:
    p2_bootstrap.form.button_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\ButtonTypeExtension
    p2_bootstrap.form.grid_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\GridTypeExtension
    p2_bootstrap.form.help_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\HelpTypeExtension
    p2_bootstrap.form.horizontal_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\HorizontalTypeExtension

services:

    # button type extension
    p2_bootstrap.form.button_type_extension:
        class: %p2_bootstrap.form.button_type_extension.class%
        tags:
            - { name: "form.type_extension", alias: "button" }

    # grid type extension
    p2_bootstrap.form.grid_type_extension:
        class: %p2_bootstrap.form.grid_type_extension.class%
        tags:
            - { name: "form.type_extension", alias: "form" }

    # help type extension
    p2_bootstrap.form.help_type_extension:
        class: %p2_bootstrap.form.help_type_extension.class%
        tags:
            - { name: "form.type_extension", alias: "form" }

    # horizontal type extension
    p2_bootstrap.form.horizontal_type_extension:
        class: %p2_bootstrap.form.horizontal_type_extension.class%
        tags:
            - { name: "form.type_extension", alias: "form" }