parameters:

    p2_bootstrap.form.extension.abstract_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\AbstractTypeExtension
    p2_bootstrap.form.extension.button_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\ButtonTypeExtension
    p2_bootstrap.form.extension.form_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\FormTypeExtension

services:

    # abstract type extension
    p2_bootstrap.form.extension.abstract_type_extension:
        class: %p2_bootstrap.form.extension.abstract_type_extension.class%
        abstract: true
        public: false
        calls:
            - [ setAllowedTypes, [ %p2_bootstrap.form.allowed_types% ]]
            - [ setAllowedValues, [ %p2_bootstrap.form.allowed_values% ]]
            - [ setDefaults, [ %p2_bootstrap.form.defaults% ]]

    # button type extension
    p2_bootstrap.form.extension.button_type_extension:
        class: %p2_bootstrap.form.extension.button_type_extension.class%
        parent: p2_bootstrap.form.extension.abstract_type_extension
        public: true
        tags:
            - { name: form.type_extension, alias: button }

    # form type extension
    p2_bootstrap.form.extension.form_type_extension:
        class: %p2_bootstrap.form.extension.form_type_extension.class%
        parent: p2_bootstrap.form.extension.abstract_type_extension
        public: true
        tags:
            - { name: form.type_extension, alias: form }
