parameters:
    p2_bootstrap.form.button_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\ButtonTypeExtension
    p2_bootstrap.form.form_type_extension.class: P2\Bundle\BootstrapBundle\Form\Extension\FormTypeExtension

services:

    # button type extension
    p2_bootstrap.form.button_type_extension:
        class: %p2_bootstrap.form.button_type_extension.class%
        tags:
            - { name: "form.type_extension", alias: "button" }

    # form type extension
    p2_bootstrap.form.form_type_extension:
        class: %p2_bootstrap.form.form_type_extension.class%
        tags:
            - { name: "form.type_extension", alias: "form" }