parameters:
    p2_bootstrap.theme_builder.class: P2\Bundle\BootstrapBundle\Themeing\ThemeBuilder
    #default_theme.class: Acme\Bundle\Themeing\DefaultTheme

services:

    p2_bootstrap.theme_builder:
        class: %p2_bootstrap.theme_builder.class%
