parameters:

    p2_bootstrap.theme.default_theme.class: P2\Bundle\BootstrapBundle\Themeing\Theme\DefaultTheme
    p2_bootstrap.theme_builder.class: P2\Bundle\BootstrapBundle\Themeing\ThemeBuilder
    p2_bootstrap.command.generate_theme.class: P2\Bundle\BootstrapBundle\Command\GenerateThemeCommand

services:

    # theme builder
    p2_bootstrap.theme_builder:
        class: %p2_bootstrap.theme_builder.class%
        arguments:
            - @templating
            - %p2_bootstrap.source_directory%
            - %p2_bootstrap.themes_directory%

    # default theme (bootstrap default style)
    p2_bootstrap.theme.default_theme:
        class: %p2_bootstrap.theme.default_theme.class%
        tags:
            - { name: bootstrap.theme }

    # generate theme command
    p2_bootstrap.command.generate_theme:
        class: %p2_bootstrap.command.generate_theme.class%
        calls:
            - [ setThemeBuilder, [ @p2_bootstrap.theme_builder ]]
